contact_links:
  - name: "\U0001F914 All other questions, including if you're not sure what to do."
    url: https://cylc.discourse.group/
    about: Search the Cylc Discourse forum for similar questions or ask for help.
